# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsYqEqeSJWqUMW68xTKJcSBlmJPP6Dms
"""

import numpy as np
import pandas as pd

# ============================================================
# HOSPITAL OPD QUEUE DATASET SIMULATION
# ============================================================

# Random seed
# Using a fixed seed means the same dataset can be reproduced.
np.random.seed(42)

# ------------------------------------------------------------
# 1. SYSTEM PARAMETERS
# ------------------------------------------------------------

NUM_PATIENTS = 300
NUM_DOCTORS = 5

# OPD operating time
OPD_START = 8 * 60       # 8:00 AM = 480 minutes
OPD_END = 16 * 60        # 4:00 PM = 960 minutes

# Peak period
PEAK_START = 8 * 60      # 8:00 AM
PEAK_END = 12 * 60       # 12:00 PM

# ------------------------------------------------------------
# 2. PATIENT TYPES
# ------------------------------------------------------------

patient_types = ["normal", "staff", "lab_report"]

# Probability of each patient type
patient_probabilities = [0.65, 0.15, 0.20]

# Priority:
# Lower number = higher priority
priority = {
    "staff": 0,
    "lab_report": 1,
    "normal": 2
}

# ------------------------------------------------------------
# 3. SERVICE TIME RANGES
# Same ranges as your friend's dataset
# ------------------------------------------------------------

service_time_ranges = {
    "normal": (8, 20),
    "staff": (5, 10),
    "lab_report": (3, 8)
}

# ------------------------------------------------------------
# 4. GENERATE PATIENT ARRIVAL TIMES
# ------------------------------------------------------------

# 70% of patients arrive during the busy period
# 8:00 AM - 12:00 PM

peak_patients = int(NUM_PATIENTS * 0.70)
off_peak_patients = NUM_PATIENTS - peak_patients

# Generate peak arrivals
peak_arrivals = np.random.uniform(
    PEAK_START,
    PEAK_END,
    peak_patients
)

# Generate off-peak arrivals
off_peak_arrivals = np.random.uniform(
    PEAK_END,
    OPD_END,
    off_peak_patients
)

# Combine arrival times
arrival_times = np.concatenate([
    peak_arrivals,
    off_peak_arrivals
])

# Sort by arrival time
arrival_times = np.sort(arrival_times)

# ------------------------------------------------------------
# 5. GENERATE PATIENT TYPES
# ------------------------------------------------------------

patient_type_list = np.random.choice(
    patient_types,
    size=NUM_PATIENTS,
    p=patient_probabilities
)

# ------------------------------------------------------------
# 6. GENERATE SERVICE TIMES
# ------------------------------------------------------------

service_times = []

for patient_type in patient_type_list:

    minimum, maximum = service_time_ranges[patient_type]

    service_time = np.random.uniform(
        minimum,
        maximum
    )

    service_times.append(service_time)

service_times = np.array(service_times)

# ------------------------------------------------------------
# 7. SIMULATE THE QUEUE
# ------------------------------------------------------------

# Each doctor's next available time
doctor_available_time = np.full(
    NUM_DOCTORS,
    OPD_START,
    dtype=float
)

# Store patients waiting in the queue
waiting_queue = []

results = []

next_patient = 0

# Continue until every patient has been served
while next_patient < NUM_PATIENTS or waiting_queue:

    # --------------------------------------------------------
    # Find next patient arrival
    # --------------------------------------------------------

    if next_patient < NUM_PATIENTS:
        next_arrival = arrival_times[next_patient]
    else:
        next_arrival = float("inf")

    # --------------------------------------------------------
    # Find doctor who becomes available first
    # --------------------------------------------------------

    doctor_index = np.argmin(doctor_available_time)

    next_doctor_available = doctor_available_time[doctor_index]

    # --------------------------------------------------------
    # If patient arrives before doctor is available,
    # add patient to waiting queue
    # --------------------------------------------------------

    if (
        next_arrival <= next_doctor_available
        and next_patient < NUM_PATIENTS
    ):

        waiting_queue.append(next_patient)

        next_patient += 1

        continue

    # --------------------------------------------------------
    # Add all patients who have arrived by this time
    # --------------------------------------------------------

    while (
        next_patient < NUM_PATIENTS
        and arrival_times[next_patient] <= next_doctor_available
    ):

        waiting_queue.append(next_patient)

        next_patient += 1

    # --------------------------------------------------------
    # If nobody is waiting, doctor waits for next patient
    # --------------------------------------------------------

    if not waiting_queue:

        doctor_available_time[doctor_index] = next_arrival

        continue

    # --------------------------------------------------------
    # SELECT PATIENT BASED ON PRIORITY
    # --------------------------------------------------------

    selected_patient = min(
        waiting_queue,
        key=lambda patient_index: (
            priority[patient_type_list[patient_index]],
            arrival_times[patient_index]
        )
    )

    waiting_queue.remove(selected_patient)

    # --------------------------------------------------------
    # SERVICE START TIME
    # --------------------------------------------------------

    arrival_time = arrival_times[selected_patient]

    service_start = max(
        arrival_time,
        next_doctor_available
    )

    # --------------------------------------------------------
    # WAITING TIME
    # --------------------------------------------------------

    waiting_time = service_start - arrival_time

    # --------------------------------------------------------
    # SERVICE TIME
    # --------------------------------------------------------

    service_time = service_times[selected_patient]

    # --------------------------------------------------------
    # SERVICE END
    # --------------------------------------------------------

    service_end = service_start + service_time

    # Update doctor availability
    doctor_available_time[doctor_index] = service_end

    # --------------------------------------------------------
    # SAVE RESULT
    # --------------------------------------------------------

    results.append({

        "patient_id":
            selected_patient + 1,

        "patient_type":
            patient_type_list[selected_patient],

        "arrival_minutes":
            arrival_time,

        "waiting_time":
            waiting_time,

        "service_time":
            service_time,

        "assign_doctor":
            f"Dr_{doctor_index + 1}"
    })


# ============================================================
# 8. CREATE DATAFRAME
# ============================================================

df = pd.DataFrame(results)

# Sort by patient ID
df = df.sort_values(
    "patient_id"
).reset_index(drop=True)


# ============================================================
# 9. CONVERT ARRIVAL TIME TO 12-HOUR FORMAT
# ============================================================

def convert_to_time(minutes):

    minutes = int(round(minutes))

    hour = minutes // 60
    minute = minutes % 60

    if hour >= 12:
        period = "PM"
    else:
        period = "AM"

    display_hour = hour

    if display_hour > 12:
        display_hour -= 12

    if display_hour == 0:
        display_hour = 12

    return f"{display_hour}:{minute:02d} {period}"


df["arrival_time"] = df["arrival_minutes"].apply(
    convert_to_time
)


# ============================================================
# 10. ROUND NUMERICAL VALUES
# ============================================================

df["waiting_time"] = df["waiting_time"].round(2)

df["service_time"] = df["service_time"].round(2)


# ============================================================
# 11. KEEP REQUIRED COLUMNS
# ============================================================

df = df[
    [
        "patient_id",
        "patient_type",
        "arrival_time",
        "waiting_time",
        "service_time",
        "assign_doctor"
    ]
]


# ============================================================
# 12. SAVE DATASET
# ============================================================

file_name = "Hospital_OPD_Queue_Dataset_300_Patients.csv"

df.to_csv(
    file_name,
    index=False
)


# ============================================================
# 13. DISPLAY RESULTS
# ============================================================

print("\nDataset successfully generated!")

print("\nFirst 10 patients:")
print(df.head(10))

print("\n---------------------------------------")

print("Total patients:", len(df))

print(
    "Average waiting time:",
    round(df["waiting_time"].mean(), 2),
    "minutes"
)

print(
    "Average service time:",
    round(df["service_time"].mean(), 2),
    "minutes"
)

print("\nPatient type distribution:")
print(df["patient_type"].value_counts())

print("\nDoctor assignment:")
print(df["assign_doctor"].value_counts())

print("\nDataset saved as:")
print(file_name)